### ISSUE TITLE
"Cannot find module 'path'" when running npm run watch

### ISSUE THREAD

**Issue by unpollito** [bitjson/typescript-starter#103]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

I have just created a typescript-starter project in my local machine (a Node application), but as soon as I try running `npm run watch`, I get a crash. node_modules/pkg-conf/index.js:1 crashes with "Error: Cannot find module 'path'".

* **Other information**

I'm using Windows 10 x64 and Node 8.9.1. The latest crash I got was with these options, although I've got it using several other configurations as well:

```
Enter the new package name: test
What are you making? Node.js application
Enter the package description: Test
Will this project use npm or yarn? npm
More fun stuff: Enable tslint-immutable, Include VS Code debugging config, Include CircleCI config
```

The installation seems to end without errors, but as soon as I run `npm run watch`, I get the following:

```
[17:48:05] Starting compilation in watch mode...

[17:48:06] Found 0 errors. Watching for file changes.

C:\Users\David\test\node_modules\pkg-conf\index.js:1
Error: Cannot find module 'path'
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\David\test\node_modules\pkg-conf\index.js:2:14)
    at Module._compile (module.js:635:30)
    at Module.replacementCompile (C:\Users\David\test\node_modules\nyc\node_modules\append-transform\index.js:58:13)
    at module.exports (C:\Users\David\test\node_modules\nyc\node_modules\default-require-extensions\js.js:8:9)
    at C:\Users\David\test\node_modules\nyc\node_modules\append-transform\index.js:62:4
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@1.0.0 test:unit: `nyc --silent ava "--watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@1.0.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\David\AppData\Roaming\npm-cache\_logs\2018-07-08T16_48_07_024Z-debug.log
ERROR: "test:unit -- --watch" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@1.0.0 watch: `run-s clean build:main && run-p "build:main -- -w" "test:unit -- --watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@1.0.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\David\AppData\Roaming\npm-cache\_logs\2018-07-08T16_48_07_122Z-debug.log
```

I'm also uploading the two log files from the crashes in case they're helpful.

[2018-07-08T16_48_07_024Z-debug.log](https://github.com/bitjson/typescript-starter/files/2173926/2018-07-08T16_48_07_024Z-debug.log)
[2018-07-08T16_48_07_122Z-debug.log](https://github.com/bitjson/typescript-starter/files/2173927/2018-07-08T16_48_07_122Z-debug.log)

**Comment by unpollito** [comment]
Apologies for this. I've finally figured out the cause.

I tried to do the same using yarn instead of npm and when installing the application, yarn complained that my Node version wasn't compatible with ava. Upon installing Node 8.11.3 (the latest stable version at this time), it started working just fine.
